### ISSUE TITLE
can i create slavenodes to replace the ram.nodes in the testtop?

### ISSUE THREAD

**Issue by user-stu-l** [OpenXiangShan/HuanCun#110]
Here is my code:
==============
.......
  def createManagerNode = {
  val slaveNode = TLManagerNode(Seq(TLSlavePortParameters.v1(
    Seq(TLSlaveParameters.v1(
      address            =  Seq(AddressSet(0xL, 0xffffL)),
      regionType         = RegionType.UNCACHED,
      resources          = new SimpleDevice("l2", Seq("sifive,maskl2")).reg("mem"),
      executable         = true,
      supportsGet        = TransferSizes(1, cacheParams.blockBytes),
      supportsPutPartial = TransferSizes(1, cacheParams.blockBytes),
      supportsPutFull    = TransferSizes(1, cacheParams.blockBytes),
      fifoId             = Some(0)
     )), 
      beatBytes  = cacheParams.blockBytes
    )
  )) 
  slaveNode
  }
....
val slave_nodes = createManagerNode
...
  for(l1d <- l1d_nodes){
    xbar := TLBuffer() := l1d
  }

  slave_nodes :=
    TLXbar() :=*
      TLFragmenter(32, 64) :=*
      TLCacheCork() :=*
      TLDelayer(delayFactor) :=*
      l2.node :=* xbar

  lazy val module = new LazyModuleImp(this){
    master_nodes.zipWithIndex.foreach{
      case (node, i) =>
        node.makeIOs()(ValName(s"master_port_$i"))
    }
   slave_nodes.makeIOs()(ValName(s"s_port"))
  }
}

====================
the problems are as follows:
====== Non-inclusive L2 (32.0KB * 1-bank) prefetch: None ======
bankBits: 0
sets:128 ways:4 blockBytes:64
[client] size:16.0KB
[client] sets:32 ways:8 blockBytes:64
blockGranularityBits: 5
usr/needHint: (1-bit)
usr/preferCache: (1-bit)
usr/alias: (2-bit)
echo/blockisdirty: (1-bit)
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed
        at ... ()
        at huancun.HuanCun$$anon$1.$anonfun$slices$2(HuanCun.scala:321)
        at scala.collection.immutable.List.map(List.scala:293)
        at huancun.HuanCun$$anon$1.$anonfun$slices$1(HuanCun.scala:319)
        at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
        at huancun.HuanCun$$anon$1.<init>(HuanCun.scala:319)
        at huancun.HuanCun.$anonfun$module$1(HuanCun.scala:233)
        at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
        at huancun.HuanCun.module$lzycompute(HuanCun.scala:233)
        at huancun.HuanCun.module(HuanCun.scala:233)
        at huancun.HuanCun.module(HuanCun.scala:170)
        at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$3(LazyModule.scala:278)
        at chisel3.Module$.do_apply(Module.scala:53)
        at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$2(LazyModule.scala:278)
        at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
        at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$1(LazyModule.scala:278)
        at scala.collection.immutable.List.flatMap(List.scala:366)
        at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate(LazyModule.scala:276)
        at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate$(LazyModule.scala:273)
        at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:335)
....
==========================

**Comment by wakafa1** [comment]
Of couse you can. Please checkout which requirement you violated and take efforts you need to make.

**Comment by user-stu-l** [comment]
> Of couse you can. Please checkout which requirement you violated and take efforts you need to make.

thank you.I am new in learning Xiangshan and chisel. so I dont konw how to change the managernode paremeter to fixed the requirement.
I found the require are as follows:
=============================
....
val slices = node.in.zip(node.out).zipWithIndex.map {
      case (((in, edgeIn), (out, edgeOut)), i) =>
        require(in.params.dataBits == out.params.dataBits)
...
=====================================
could you give me some advice?

**Comment by wakafa1** [comment]
You can refer to https://github.com/OpenXiangShan/HuanCun/tree/testtop-standalone. I implement a slave node as port in TestTop_L2_Standalone
