### ISSUE TITLE
make test error, tried with java 1.8.0_292 and java 11, ubuntu16.04

### ISSUE THREAD

**Issue by iamdotasb** [OpenXiangShan/HuanCun#93]
VirtualBox:~/cache_str/HuanCun$ make test
mill -i HuanCun.test.test
[164/164] HuanCun.test.test 
====== Non-inclusive L2 (32.0KB * 1-bank) prefetch: true ======
bankBits: 0
sets:128 ways:4 blockBytes:64
[client] size:16.0KB
[client] sets:32 ways:8 blockBytes:64
usr/needHint: (1-bit)
usr/preferCache: (1-bit)
clientBits: 1
Data ECC bits:0
Tag ECC bits:0
Tag ECC bits:0
	0 <= L1D-bank0
	1 <= L1I-bank0
	2 <= PTW-bank0
AllocatorTest:
L2
huancun.AllocatorTest *** ABORTED ***
  java.lang.NoClassDefFoundError: chisel3/MultiIOModule
  at chiseltest.internal.VerilatorBackendAnnotation$.<init>(Testers2.scala:127)
  at chiseltest.internal.VerilatorBackendAnnotation$.<clinit>(Testers2.scala)
  at chiseltest.experimental.ChiselTestCli.$init$(ChiselTestShell.scala:16)
  at chiseltest.experimental.ChiselTestShell.<init>(ChiselTestShell.scala:22)
  at chiseltest.ChiselScalatestTester$TestBuilder.apply(ChiselScalatestTester.scala:26)
  at huancun.AllocatorTest.$anonfun$new$2(AllocatorTest.scala:19)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
  Cause: java.lang.ClassNotFoundException: chisel3.MultiIOModule
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at mill.api.ClassLoader$$anon$1.findClass(ClassLoader.scala:43)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  at chiseltest.internal.VerilatorBackendAnnotation$.<init>(Testers2.scala:127)
  at chiseltest.internal.VerilatorBackendAnnotation$.<clinit>(Testers2.scala)
  at chiseltest.experimental.ChiselTestCli.$init$(ChiselTestShell.scala:16)
  at chiseltest.experimental.ChiselTestShell.<init>(ChiselTestShell.scala:22)
  at chiseltest.ChiselScalatestTester$TestBuilder.apply(ChiselScalatestTester.scala:26)
  at huancun.AllocatorTest.$anonfun$new$2(AllocatorTest.scala:19)
  ...
java.lang.NoClassDefFoundError: chisel3/MultiIOModule
java.lang.NoClassDefFoundError: chisel3/MultiIOModule
	at chiseltest.internal.VerilatorBackendAnnotation$.<init>(Testers2.scala:127)
	at chiseltest.internal.VerilatorBackendAnnotation$.<clinit>(Testers2.scala)
	at chiseltest.experimental.ChiselTestCli.$init$(ChiselTestShell.scala:16)
	at chiseltest.experimental.ChiselTestShell.<init>(ChiselTestShell.scala:22)
	at chiseltest.ChiselScalatestTester$TestBuilder.apply(ChiselScalatestTester.scala:26)
	at huancun.AllocatorTest.$anonfun$new$2(AllocatorTest.scala:19)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1684)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at huancun.L2Tester.chiseltest$ChiselScalatestTester$$super$withFixture(L2Tester.scala:13)
	at chiseltest.ChiselScalatestTester.$anonfun$withFixture$1(ChiselScalatestTester.scala:50)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at chiseltest.ChiselScalatestTester.withFixture(ChiselScalatestTester.scala:50)
	at chiseltest.ChiselScalatestTester.withFixture$(ChiselScalatestTester.scala:47)
	at huancun.L2Tester.withFixture(L2Tester.scala:13)
	at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1682)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1694)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1694)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1676)
	at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1752)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1752)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1751)
	at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1797)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1797)
	at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1795)
	at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
	at mill.scalalib.TestRunner$.$anonfun$runTestFramework$2(TestRunner.scala:251)
	at mill.modules.Jvm$.inprocess(Jvm.scala:254)
	at mill.scalalib.TestRunner$.runTestFramework(TestRunner.scala:214)
	at mill.scalalib.TestRunner$.main(TestRunner.scala:162)
	at mill.scalalib.TestRunner.main(TestRunner.scala)
Caused by: java.lang.ClassNotFoundException: chisel3.MultiIOModule
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at mill.api.ClassLoader$$anon$1.findClass(ClassLoader.scala:43)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 55 more
1 targets failed
HuanCun.test.test Test execution failed.
Makefile:9: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by wakafa1** [comment]
`make test` is a deprecated command now. We will fix it later.

**Comment by iamdotasb** [comment]
Well, so how to run module level test?

**Comment by wakafa1** [comment]
Our testing framework is under development now (a new repo) and will be made public in due time

**Comment by erdevonmatteo11** [comment]
which command is ok to use for module level test? would you mind showing us?

**Comment by wakafa1** [comment]
Now our UT environment is available. Please check out https://github.com/OpenXiangShan/tl-test.
